# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\Employee Folders\Josh\Programs\Clocking\Gui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 613)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clockTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.clockTableWidget.setObjectName("clockTableWidget")
        self.clockTableWidget.setColumnCount(0)
        self.clockTableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.clockTableWidget, 3, 1, 1, 3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(0)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 1, 1, 3)
        self.clockButton = QtWidgets.QPushButton(self.centralwidget)
        self.clockButton.setObjectName("clockButton")
        self.gridLayout_2.addWidget(self.clockButton, 4, 1, 1, 3)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.userBox = QtWidgets.QComboBox(self.centralwidget)
        self.userBox.setEditable(False)
        self.userBox.setObjectName("userBox")
        self.gridLayout_3.addWidget(self.userBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.categoryBox = QtWidgets.QComboBox(self.centralwidget)
        self.categoryBox.setObjectName("categoryBox")
        self.gridLayout_3.addWidget(self.categoryBox, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 4, 1, 1)
        self.addCategoryButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCategoryButton.setObjectName("addCategoryButton")
        self.gridLayout_3.addWidget(self.addCategoryButton, 1, 7, 1, 1)
        self.addUserButton = QtWidgets.QPushButton(self.centralwidget)
        self.addUserButton.setObjectName("addUserButton")
        self.gridLayout_3.addWidget(self.addUserButton, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 1, 3, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(5, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuButtons = QtWidgets.QMenu(self.menubar)
        self.menuButtons.setObjectName("menuButtons")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAdd_Button = QtWidgets.QAction(MainWindow)
        self.actionAdd_Button.setObjectName("actionAdd_Button")
        self.actionExport_Invoice = QtWidgets.QAction(MainWindow)
        self.actionExport_Invoice.setObjectName("actionExport_Invoice")
        self.actionAdd_User = QtWidgets.QAction(MainWindow)
        self.actionAdd_User.setObjectName("actionAdd_User")
        self.actionAdd_Category = QtWidgets.QAction(MainWindow)
        self.actionAdd_Category.setObjectName("actionAdd_Category")
        self.menuFile.addAction(self.actionAdd_User)
        self.menuFile.addAction(self.actionAdd_Category)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExport_Invoice)
        self.menuButtons.addAction(self.actionAdd_Button)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuButtons.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Category:"))
        self.label_4.setText(_translate("MainWindow", "User:"))
        self.clockButton.setText(_translate("MainWindow", "Clock In"))
        self.label.setText(_translate("MainWindow", "User"))
        self.label_2.setText(_translate("MainWindow", "Category"))
        self.addCategoryButton.setText(_translate("MainWindow", "Add Category"))
        self.addUserButton.setText(_translate("MainWindow", "Add User"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuButtons.setTitle(_translate("MainWindow", "Buttons"))
        self.actionAdd_Button.setText(_translate("MainWindow", "Add Button"))
        self.actionExport_Invoice.setText(_translate("MainWindow", "Export Invoice"))
        self.actionAdd_User.setText(_translate("MainWindow", "Add User"))
        self.actionAdd_Category.setText(_translate("MainWindow", "Add Category"))

