# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Josh\PycharmProjects\Clocking\Gui\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 603)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(0, -1, 0, -1)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.clockTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clockTableWidget.setFont(font)
        self.clockTableWidget.setTextElideMode(QtCore.Qt.ElideRight)
        self.clockTableWidget.setObjectName("clockTableWidget")
        self.clockTableWidget.setColumnCount(0)
        self.clockTableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.clockTableWidget, 3, 1, 1, 3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setContentsMargins(6, 0, 6, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_5.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.globalRadioButton = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.globalRadioButton.setFont(font)
        self.globalRadioButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.globalRadioButton.setObjectName("globalRadioButton")
        self.gridLayout_5.addWidget(self.globalRadioButton, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_2, 0, 4, 1, 1)
        self.userLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.userLabel.setFont(font)
        self.userLabel.setObjectName("userLabel")
        self.gridLayout_4.addWidget(self.userLabel, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 1, 1, 1)
        self.categoryLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.categoryLabel.setFont(font)
        self.categoryLabel.setLineWidth(1)
        self.categoryLabel.setMidLineWidth(0)
        self.categoryLabel.setObjectName("categoryLabel")
        self.gridLayout_4.addWidget(self.categoryLabel, 0, 3, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_4.addWidget(self.line_4, 0, 7, 1, 1)
        self.totalIncomeLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.totalIncomeLabel.setFont(font)
        self.totalIncomeLabel.setObjectName("totalIncomeLabel")
        self.gridLayout_4.addWidget(self.totalIncomeLabel, 0, 8, 1, 1)
        self.totalTimeLabel = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.totalTimeLabel.setFont(font)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.gridLayout_4.addWidget(self.totalTimeLabel, 0, 5, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 1)
        self.gridLayout_4.setColumnStretch(3, 1)
        self.gridLayout_4.setColumnStretch(5, 1)
        self.gridLayout_4.setColumnStretch(8, 1)
        self.gridLayout_2.addWidget(self.frame, 1, 1, 1, 3)
        self.clockButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clockButton.sizePolicy().hasHeightForWidth())
        self.clockButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.clockButton.setFont(font)
        self.clockButton.setObjectName("clockButton")
        self.gridLayout_2.addWidget(self.clockButton, 4, 1, 1, 3)
        self.gridLayout_2.setRowMinimumHeight(4, 50)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.userBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.userBox.setFont(font)
        self.userBox.setEditable(False)
        self.userBox.setObjectName("userBox")
        self.gridLayout_3.addWidget(self.userBox, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.categoryBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.categoryBox.setFont(font)
        self.categoryBox.setObjectName("categoryBox")
        self.gridLayout_3.addWidget(self.categoryBox, 1, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 4, 1, 1)
        self.addCategoryButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addCategoryButton.setFont(font)
        self.addCategoryButton.setObjectName("addCategoryButton")
        self.gridLayout_3.addWidget(self.addCategoryButton, 1, 7, 1, 1)
        self.addUserButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addUserButton.setFont(font)
        self.addUserButton.setObjectName("addUserButton")
        self.gridLayout_3.addWidget(self.addUserButton, 1, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 1, 3, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_3.setColumnStretch(5, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuButtons = QtWidgets.QMenu(self.menubar)
        self.menuButtons.setObjectName("menuButtons")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuEmailing = QtWidgets.QMenu(self.menubar)
        self.menuEmailing.setObjectName("menuEmailing")
        MainWindow.setMenuBar(self.menubar)
        self.actionAdd_Button = QtWidgets.QAction(MainWindow)
        self.actionAdd_Button.setObjectName("actionAdd_Button")
        self.actionExport_Invoice = QtWidgets.QAction(MainWindow)
        self.actionExport_Invoice.setShortcutVisibleInContextMenu(True)
        self.actionExport_Invoice.setObjectName("actionExport_Invoice")
        self.actionAdd_User = QtWidgets.QAction(MainWindow)
        self.actionAdd_User.setObjectName("actionAdd_User")
        self.actionAdd_Category = QtWidgets.QAction(MainWindow)
        self.actionAdd_Category.setObjectName("actionAdd_Category")
        self.categoryAddAction = QtWidgets.QAction(MainWindow)
        self.categoryAddAction.setObjectName("categoryAddAction")
        self.categoryDeleteAction = QtWidgets.QAction(MainWindow)
        self.categoryDeleteAction.setObjectName("categoryDeleteAction")
        self.categoryEditAction = QtWidgets.QAction(MainWindow)
        self.categoryEditAction.setObjectName("categoryEditAction")
        self.userAddAction = QtWidgets.QAction(MainWindow)
        self.userAddAction.setObjectName("userAddAction")
        self.userEditAction = QtWidgets.QAction(MainWindow)
        self.userEditAction.setObjectName("userEditAction")
        self.userDeleteAction = QtWidgets.QAction(MainWindow)
        self.userDeleteAction.setObjectName("userDeleteAction")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setShortcutVisibleInContextMenu(True)
        self.actionPreferences.setObjectName("actionPreferences")
        self.userAddAction_2 = QtWidgets.QAction(MainWindow)
        self.userAddAction_2.setShortcutVisibleInContextMenu(True)
        self.userAddAction_2.setObjectName("userAddAction_2")
        self.actionEdit_User = QtWidgets.QAction(MainWindow)
        self.actionEdit_User.setShortcutVisibleInContextMenu(True)
        self.actionEdit_User.setObjectName("actionEdit_User")
        self.actionDelete_User = QtWidgets.QAction(MainWindow)
        self.actionDelete_User.setShortcutVisibleInContextMenu(True)
        self.actionDelete_User.setObjectName("actionDelete_User")
        self.actionAdd_Category_2 = QtWidgets.QAction(MainWindow)
        self.actionAdd_Category_2.setShortcutVisibleInContextMenu(True)
        self.actionAdd_Category_2.setObjectName("actionAdd_Category_2")
        self.actionEdit_Category = QtWidgets.QAction(MainWindow)
        self.actionEdit_Category.setShortcutVisibleInContextMenu(True)
        self.actionEdit_Category.setObjectName("actionEdit_Category")
        self.actionDelete_Category = QtWidgets.QAction(MainWindow)
        self.actionDelete_Category.setShortcutVisibleInContextMenu(True)
        self.actionDelete_Category.setObjectName("actionDelete_Category")
        self.actionExport_All_Invoices = QtWidgets.QAction(MainWindow)
        self.actionExport_All_Invoices.setShortcutVisibleInContextMenu(True)
        self.actionExport_All_Invoices.setObjectName("actionExport_All_Invoices")
        self.actionClock = QtWidgets.QAction(MainWindow)
        self.actionClock.setShortcutVisibleInContextMenu(True)
        self.actionClock.setObjectName("actionClock")
        self.actionAssign_Buttons = QtWidgets.QAction(MainWindow)
        self.actionAssign_Buttons.setObjectName("actionAssign_Buttons")
        self.actionSet_Email_Template = QtWidgets.QAction(MainWindow)
        self.actionSet_Email_Template.setObjectName("actionSet_Email_Template")
        self.actionAssign_Days_to_Send_Emails = QtWidgets.QAction(MainWindow)
        self.actionAssign_Days_to_Send_Emails.setObjectName("actionAssign_Days_to_Send_Emails")
        self.actionSet_Default_Invoice_Path = QtWidgets.QAction(MainWindow)
        self.actionSet_Default_Invoice_Path.setObjectName("actionSet_Default_Invoice_Path")
        self.actionSetup_Emailing = QtWidgets.QAction(MainWindow)
        self.actionSetup_Emailing.setObjectName("actionSetup_Emailing")
        self.actionSet_Users_Invoices_to_Email = QtWidgets.QAction(MainWindow)
        self.actionSet_Users_Invoices_to_Email.setObjectName("actionSet_Users_Invoices_to_Email")
        self.actionEMail_Now = QtWidgets.QAction(MainWindow)
        self.actionEMail_Now.setObjectName("actionEMail_Now")
        self.actionSet_Company = QtWidgets.QAction(MainWindow)
        self.actionSet_Company.setObjectName("actionSet_Company")
        self.menuFile.addAction(self.actionExport_Invoice)
        self.menuFile.addAction(self.actionExport_All_Invoices)
        self.menuFile.addAction(self.actionSet_Default_Invoice_Path)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionPreferences)
        self.menuButtons.addAction(self.actionAdd_Button)
        self.menuButtons.addAction(self.actionAssign_Buttons)
        self.menuEdit.addAction(self.userAddAction_2)
        self.menuEdit.addAction(self.actionEdit_User)
        self.menuEdit.addAction(self.actionDelete_User)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionAdd_Category_2)
        self.menuEdit.addAction(self.actionEdit_Category)
        self.menuEdit.addAction(self.actionDelete_Category)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSet_Company)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClock)
        self.menuEmailing.addAction(self.actionEMail_Now)
        self.menuEmailing.addSeparator()
        self.menuEmailing.addAction(self.actionSetup_Emailing)
        self.menuEmailing.addSeparator()
        self.menuEmailing.addAction(self.actionSet_Email_Template)
        self.menuEmailing.addAction(self.actionAssign_Days_to_Send_Emails)
        self.menuEmailing.addAction(self.actionSet_Users_Invoices_to_Email)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuEmailing.menuAction())
        self.menubar.addAction(self.menuButtons.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clocking"))
        self.globalRadioButton.setText(_translate("MainWindow", "Global"))
        self.userLabel.setText(_translate("MainWindow", "User:"))
        self.categoryLabel.setText(_translate("MainWindow", "Category:"))
        self.totalIncomeLabel.setText(_translate("MainWindow", "Total Income:"))
        self.totalTimeLabel.setText(_translate("MainWindow", "Total Time:"))
        self.clockButton.setText(_translate("MainWindow", "Clock In"))
        self.label.setText(_translate("MainWindow", "User"))
        self.label_2.setText(_translate("MainWindow", "Category"))
        self.addCategoryButton.setText(_translate("MainWindow", "Add Category"))
        self.addUserButton.setText(_translate("MainWindow", "Add User"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuButtons.setTitle(_translate("MainWindow", "Buttons"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuEmailing.setTitle(_translate("MainWindow", "Emailing"))
        self.actionAdd_Button.setText(_translate("MainWindow", "Add Button"))
        self.actionExport_Invoice.setText(_translate("MainWindow", "Export Invoice"))
        self.actionExport_Invoice.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionAdd_User.setText(_translate("MainWindow", "Add User"))
        self.actionAdd_Category.setText(_translate("MainWindow", "Add Category"))
        self.categoryAddAction.setText(_translate("MainWindow", "Add"))
        self.categoryDeleteAction.setText(_translate("MainWindow", "Delete"))
        self.categoryEditAction.setText(_translate("MainWindow", "Edit"))
        self.userAddAction.setText(_translate("MainWindow", "Add"))
        self.userEditAction.setText(_translate("MainWindow", "Edit"))
        self.userDeleteAction.setText(_translate("MainWindow", "Delete"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.userAddAction_2.setText(_translate("MainWindow", "Add User"))
        self.userAddAction_2.setShortcut(_translate("MainWindow", "Ctrl+Shift+A"))
        self.actionEdit_User.setText(_translate("MainWindow", "Edit User"))
        self.actionEdit_User.setShortcut(_translate("MainWindow", "Ctrl+Shift+E"))
        self.actionDelete_User.setText(_translate("MainWindow", "Delete User"))
        self.actionDelete_User.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionAdd_Category_2.setText(_translate("MainWindow", "Add Category"))
        self.actionAdd_Category_2.setShortcut(_translate("MainWindow", "Ctrl+Alt+A"))
        self.actionEdit_Category.setText(_translate("MainWindow", "Edit Category"))
        self.actionEdit_Category.setShortcut(_translate("MainWindow", "Ctrl+Alt+E"))
        self.actionDelete_Category.setText(_translate("MainWindow", "Delete Category"))
        self.actionDelete_Category.setShortcut(_translate("MainWindow", "Ctrl+Alt+D"))
        self.actionExport_All_Invoices.setText(_translate("MainWindow", "Export All Invoices"))
        self.actionExport_All_Invoices.setShortcut(_translate("MainWindow", "Ctrl+Shift+I"))
        self.actionClock.setText(_translate("MainWindow", "Clock"))
        self.actionClock.setShortcut(_translate("MainWindow", "Ctrl+Space"))
        self.actionAssign_Buttons.setText(_translate("MainWindow", "Assign Buttons"))
        self.actionSet_Email_Template.setText(_translate("MainWindow", "Set Email Template"))
        self.actionAssign_Days_to_Send_Emails.setText(_translate("MainWindow", "Assign Days to Send Emails"))
        self.actionSet_Default_Invoice_Path.setText(_translate("MainWindow", "Set Default Invoice Path"))
        self.actionSetup_Emailing.setText(_translate("MainWindow", "Set Emailing"))
        self.actionSet_Users_Invoices_to_Email.setText(_translate("MainWindow", "Set Users Invoices to Email"))
        self.actionEMail_Now.setText(_translate("MainWindow", "Email Now"))
        self.actionSet_Company.setText(_translate("MainWindow", "Set Company"))
